### ISSUE TITLE
Util as a lib - linker double difinition error

### ISSUE THREAD

**Issue by BBasile** [DerelictOrg/DerelictUtil#10]
Would it be possible to build a project based on a derelict item with DerelictUtil build as a lib ?
Currently this produces these kind of messages:

>
..Error: multiple definition of exception: _D8derelict4util9exception22SharedLibLoadException13sharedLibNameMFZAya and exception: _D8derelict4util9exception22SharedLibLoadException13sharedLibNameMFZAya
..\lib\sdg.lib: Error: multiple definition of exception: _D8derelict4util9exception19SymbolLoadException6__initZ and exception: _D8derelict4util9exception19SymbolLoadException6__initZ
..\lib\sdg.lib: Error: multiple definition of exception: _D8derelict4util9exception19SymbolLoadException7__ClassZ and exception: _D8derelict4util9exception19SymbolLoadException7__ClassZ

To be clear:
- **✓**: DerelictUtil is build as a lib
- **✓**: DerelictXXX is build with this DerelictUtil.lib + its base path passed as source + search path: 
- **✕** MyProjectTruc is build with DerelictUtil.lib + DerelicXXX.lib + their base paths passed as source + search path and then i get the errors messages unless i remove DerelictUtil.lib from the sources...

It seems the the symbols are copied in DerelictXXX when it's build, is it necessary ? couldn't it remain in DerelictUtil ?

(DMD, win32)

**Comment by aldacron** [comment]
Keep in mind that when you build DerelictXXX with DUB, it's using whichever version of DerelictUtil is in your DUB cache. I'm guessing your problem is that DerelictUtil 1.0.x is in your cache, DerelictXXX is happy to build against it, then you're building the master branch of DerelictUtil and linking that with your app. DerelictUtil master is currently the same as the 2.0 branch, which is tagged as 2.0.0 in the DUB registry. It's binary incompatible with 1.0.x. Here's what you should do:

1) cd into the DerelictXXX project directory
2) dub upgrade
3) dub build, making sure that it's using DerelictUtil 2.0.0
4) cd into the DerelictUtil project directory
5) git checkout 2.0 -- this isn't strictly necessary at the moment as the master branch is in sync with the 2.0 branch, but development work is done in master so that could change (I'll go ahead and set 2.0 as the default branch after I leave this comment)
6) dub build

With this, your manually-built DerelictUtil and your cached version should match. Eventually, all Derelict projects will require DerelictUtil 2.0.0 and this problem can be avoided.

Please let me know if this fixes it for you, as I'm just making an educated guess.

**Comment by BBasile** [comment]
I should have precised that i'm not using DUB, i'm using Coedit project format and the [meta D repository](https://github.com/BBasile/metad), which follows the GIT master of each item. So Util and XXX are up to date.

Here is a list of the options passed to DMD when i compile MyProject truc:

>
C:\Dev\dproj\sdg\import\sdg\types.d
C:\Dev\dproj\sdg\import\sdg\backend.d
C:\Dev\dproj\sdg\import\sdg\backends\sdl2.d
C:\Dev\dproj\sdg\import\sdg\primitives.d
C:\Dev\dproj\sdg\import\sdg\layouts.d
C:\Dev\metad\libs\DerelictGL3.lib
C:\Dev\metad\libs\DerelictSDL2.lib
C:\Dev\metad\libs\DerelictUtil.lib
C:\Dev\dproj\iz\lib\iz.lib
-IC:\Dev\metad\repos\DerelictOrg\DerelictGL3\source
-IC:\Dev\metad\repos\DerelictOrg\DerelictSDL2\source
-IC:\Dev\metad\repos\DerelictOrg\DerelictUtil\source
-IC:\Dev\dproj\iz\import
-w
-lib
-inline
-O
-boundscheck=off
-of..\lib\sdg

this generates two dozen of error messages similar to those copied and paste in the initial report.

and it compiles fine if i remove
> C:\Dev\metad\libs\DerelictUtil.lib

because as explained before it contains some Exceptions symbols that are already defined in DerelictGL3.lib and DerelictSDL2.lib

my Q is: can something can be done to the Derelict system to avoid this problem ? I think to some tweaks based on version(something) and maybe some template ?

**Comment by aldacron** [comment]
>> and it compiles fine if i remove
It shouldn't compile fine without DerelictUtil. It's absolutely required. It almost sounds like DerelictUtil is being compiled into the DerelictSDL2 or DerelictGL3 library. Does Coedit automatically compile and archive imported files? If it works without linking DerelictUtil, that's the only thing I can think of. In which case, you don't need to link with DerelictUtil.

>> an something can be done to the Derelict system to avoid this problem ? I think to some tweaks based on version(something) and maybe some template ?
This appears to be a build system issue. DUB is the only system I support or will support. I just don't have time to do otherwise.

**Comment by BBasile** [comment]
What a mess... i just get the issue

for example this is the options passed to DMD to compile DerelictFI:

>
C:\Dev\metad\repos\DerelictOrg\DerelictFI\source\derelict\freeimage\freeimage.d
C:\Dev\metad\repos\DerelictOrg\DerelictFI\source\derelict\freeimage\functions.d
C:\Dev\metad\repos\DerelictOrg\DerelictFI\source\derelict\freeimage\types.d
C:\Dev\metad\libs\DerelictUtil.lib
-IC:\Dev\metad\repos\DerelictOrg\DerelictUtil\source
-w
-lib
-inline
-O
-release
-boundscheck=off
-of..\libs\DerelictFI

Util is linked, a DerelictXXX compiles fine if i just specify the import.

**Comment by aldacron** [comment]
You don't need to pass DerelictUtil.lib when building the Derelict packages, only when building your executable. In fact, I just did a little test and I was surprised to learn that with the -lib option, DMD actually does combine any libraries it's given into the one it is creating. So if you're going to link with DerelictUtil, you *shouldn't* pass it when compiling the other Derelict packages.
