### ISSUE TITLE
A runtime-free Derelict as a configuration?

### ISSUE THREAD

**Issue by p0nce** [DerelictOrg/DerelictUtil#17]
Hi @mdparker ,

Over the course of a complicated course of events (https://github.com/AuburnSounds/dplug/issues/129), it appears I have to run without the runtime initialized (let's call it "runtime-free" as opposed to "runtime-less"?). That means no GC, no global ctor/dtor, no slice literals, and no TLS. As it appears quite a lot of things can run without the runtime already though.

As I understand it, Derelict uses:
- `shared static this()` for initializing loaders,
- the GC for exceptions
- slice concatenation

Are you OK with me exploring this possibility in the form of a PR?

Unknown symbols could be handled either with a static exception (Error) or with `assert(false)` instead (both are acceptable for this use case).

Loaders can be created and destroyed without the runtime enabled, provided they don't throw in their destructors.

This could be a DUB configuration, then selectable with `subConfigurations` in dependent packages. I think this is something Mir would also stumble upon if they want to go runtime-free.

The goal is to be able to use DerelictCocoa and DerelictCarbon without runtime.

**Comment by mdparker** [comment]
Knock yourself out! But I do recommend using the 3.0 branch. Now that I've applied the __FILE__ and __LINE__ parameters to the exception constructors, I don't believe there's anything else to be added.

I'm going to slowly get all of the other packages configured to use it (so far, SDL2, GL3, GLFW3 and FI all have branches using it). Most packages aren't going to require anything more than updating dub.sdl/json with a 3.0.0 dependency. There's not much new to it. I've exposed the bindFunc method so that packages can call DerelictFoo.bindFunc without needing to be inside loadSymbols, and I've also added a public bindFunc_stdcall method (which is the old internal FreeImage loader that you recommended I expose). Other than that, I added @nogc and nothrow where appropriate and cut a lot of cruft. 

What I've been doing locally is, once I add a support for it to a package, I do a add-local with a new version and keep it on that branch by default. So I'm currently using DerelictGL3 2.0.0, DerelictSDL2 2.1.0 and DerelictUtil 3.0.0 locally, all of which have branches in the origin, but none of which have been released.

Anyway, since I intend to release 3.0.0 before the end of this year, that's where you should focus your efforts.

**Comment by p0nce** [comment]
OK. It's pretty cool that `bindFunc_stdcall` made it. All my Derelict bindings use `~>` so you can release DerelictUtil v3.0 whenever you want. It's a bit of a bummer it isn't out already, and you know my stance about `>=`.

I'm not sure if I have understood. Would you merge a configuration which doesn't use the runtime, provided it meets your requirements? Only for v3 I guess?

I have customers waiting for the new products without runtime, so in this particular hurry, and in order to keep the build system simple, I may have to put some temporary package `dplug:derelict-util-nogc` or something like that. Hiding it in `dplug` so that it doesn't get used.
Hopefully this will solve nicely once v3 is out.

**Comment by mdparker** [comment]
> It's a bit of a bummer it isn't out already, and you know my stance about >=.

Indeed. Unfortunately, there are going to be people out there using >= so they will inevitably wind up with one package that has been updated to use DerelictUtil 3.0 mixed in the same project with one that hasn't. I can't do anything about third-party packages, but at least I can control the main repo.

> I'm not sure if I have understood. Would you merge a configuration which doesn't use the runtime, provided it meets your requirements? Only for v3 I guess?

Yes and yes.

> Hopefully this will solve nicely once v3 is out!

I'll try to speed that up a bit. I've been taking it lazily so far because no one that I know of has been waiting for it. But I've got a pile of stuff to work through these days in addition to Derelict (and age has made me acutely aware of just how short 24 hours really is), little of which I can drop completely. But I can at least give DerelictUtil more priority than the game I'm working on (and, I suppose, the DUB book) so that I can get it out earlier than I had intended. Now that the refactoring of DerelictGL3 is complete, it shouldn't take too much time to update the remaining packages. DerelictGLES will take a bit of work, since I want to refactor it, too, but I've never really considered it complete anyway and I won't let it hold anything up.

**Comment by p0nce** [comment]
Thanks. I'll do my best to provide such a configuration in a way that is acceptable.

What we can do for the release of the derelict-util v3 tag is to release for each Derelict package:
- **Now:** a minor tag using `"derelict-util": "~>2.0"`. That way most users will still use derelict-util 2.x.y in a way that is non-breaking. Anyone using ~> for eg. derelict-gl3 will be protected from tag breakage.
- **After v3.0.0 is tagged:** a major version tag using `"derelict-util": "~>3.0"`. Because changing the major derelict-util version is often breaking.

Whoever has a build still breaking will be able to use the new major tag.

**Comment by mdparker** [comment]
I learned my lesson about >= when I released Util 2.0. Most everything here should be using ~>2.0.x already, with the exception of a couple or three I haven't touched in ages. Like the ASSIMP binding, which still has an old package.json with a >=1.0.0 Util dependency!

**Comment by mdparker** [comment]
I was on the mobile version of the site earlier, which lists the repositories in alphabetical order. Now that I'm home, I see you've saved me the trouble of going through everything. FI and FT surprised me. I've even got a branch of FI for Util 3.0 and didn't catch it.

My plan is to make sure each package is caught up with the latest version its C library before making a new branch, so I'll get the dependencies fixed as I go. I'll do FI now, since I know it's up to date.

**Comment by p0nce** [comment]
Yup. There was no new ENet release so the version was a simple bump.

**Comment by p0nce** [comment]
Hi @mdparker,

For now, the fork exist as `dplug:derelict-nogc`. https://github.com/AuburnSounds/dplug/tree/master/derelictnogc/derelict/util

 What has changed is that there is an added file `nogc.d` for utility functions.
DUB seems to select sub-configuration correctly and propagates the right `-version`.
The loader doesn't throw exception for missing symbols but `assert(false)`.
The fact of emplacing the loader is then left as an exercise for the user.

The biggest pain point is that the interface of `SharedLibLoader` and `SharedLib` has heavy duplication, because you can't make a function `nothrow @nogc` depending on a version. Attribute inference didn't work out as I thought it would.

**Comment by mdparker** [comment]
Alright. Looking at your implementation has triggered a thought. I think we can just make the whole thing `@nogc` without changing the way things work normally. The only additional burden would be that anytime a DerelictException is caught, it should be manually freed if the program doesn't exit, most likely through a `release` method. I think such an occurrence is rare enough that, even if not freed, there isn't much danger of massive memory leaks, so it really isn't much of a burden at all. 

I'll get something together in the next few days.

**Comment by p0nce** [comment]
One of the major blockers of @nogc is that calling an class destructor isn't `nothrow`and `@nogc`. `object.destroy()` isn't @nogc and I have to cast it to `@nogc` which is a hack.

See the implementation of `mallocEmplace` and `destroyFree` in https://github.com/AuburnSounds/dplug/blob/master/core/dplug/core/nogc.d#L155
I don't know if there is a way to have class objects in @nogc code without cheating. Then again, I haven't found how.

**Comment by mdparker** [comment]
Ah, right. A while back I tried to port an old C vector container implementation using std.experimental.mallocator, tried to make it all @nogc, and ran into trouble with deallocation. I even had a discussion about it with Jonathan and Steve at DConf and still forgot all about it.

**Comment by mdparker** [comment]
Thinking some more. It should be possible to convert the loaders to structs using alias this for the base implementation. Exceptions can be allocated via malloc + emplace, then deallocated directly with free when user code catches without aborting. Given that their destructors do nothing anyway, there should be no consequences to not calling destroy, correct?

**Comment by p0nce** [comment]
This will leak but I think it's OK in Derelict exceptions cases which aren't numerous.
Manual exceptions have the following downside : you must find an owner to the string (the exception?) or only pass string literals to such exceptions.

Another challenge is that when not using runtime you cannot rely on global constructors (or TLS). I use a counter and static functions to create the @nogc loader, but haven't find a clean way to make it thread-safe. https://github.com/AuburnSounds/dplug/blob/master/cocoa/derelict/cocoa/cocoa.d#L114

**Comment by mdparker** [comment]
> This will leak
Yes, but I'm talking about adding a means to the API to release it.

> you must find an owner to the string
Not a problem. 

> Another challenge is that when not using the runtime you cannot rely on global constructors 
With structs this problem goes away, no?

> So this changes the API for package who uses derelict-util.
Yes. But it's a new major version anyway.

**Comment by p0nce** [comment]
> With structs this problem goes away, no?
It is pushed on the user. For the common case of using Derelict for an application, not a problem indeed.

WIth structs, noone will be able to rely on the GC for deleting their resources anymore (dynlib will be unloaded by then), which is a net gain.

**Comment by p0nce** [comment]
Now that I think of it, I'm too much ignorant of the facilities in Phobos. There might be something there that converts a class in a @nogc struct.

**Comment by mdparker** [comment]
I can see a way forward with this, but the more I think about it, the less I'm certain about doing it. What I have in mind is:

* Change SharedLibLoader into a struct. Eliminate all of the load methods but one, which would now take a const(char)* instead of a string, along with a loadSymbols delegate.
* Create a SharedLibLoaderImpl mixin which mixes in a SharedLibLoader member and another load method forwards to SharedLibLoader.load. It will require loadSymbols to exist in the surrounding scope.
* Package-specific loaders now become:
```d
struct DerelictSDL2Loader {
    mixin!SharedLibLoaderImpl;
    void loadSymbols @nogc { ... }
}
```
* Allocate exceptions via malloc, give DerelictException a static release method, and use free to clean up without calling destructors (otherwise it can't be @nogc).
* Go through DerelictUtil and DerelictGL3 to eliminate every instance of GC-based string and array manipulation (appending, calls to format, etc). Replace it all with C standard library calls and pointer manipulation.

If I were initiating DerelictUtil today and we were having this conversation, it would be a no-brainer. What I worry about is all of the third-party Derelict packages out there. With my current implementation of DerelictUtil 3.0, they only need to change the dependency in their dub configs to be compatible with other packages using the new version. Changes like I've outlined above would require a complete reimplementation. I'm willing to make it happen if it's worth it, but yours is the only use-case I've heard of so far.

So rather than rearchitecting DerelictUtil or making an alternate configuration, how about an entirely new package? DerelictUtilNOGC. It can use a different type name for the loader and can have its own exceptions which sublcass the existing Derelict exceptions. Then, it can live side-by-side with the current package in the same program, for those that need it, and no existing packages need to be rearchitected.

Thoughts?

**Comment by p0nce** [comment]
Hi, it's true that it's a niche requirement, I wasn't even forced to part with the runtime, there were alternatives. 

I'm fully OK with the minimal cost of having a small @nogc derelict-util in `dplug:derelict-nogc`, and the license stays Boost anyway. I don't think it's worth it for derelict either! This change is too encompassing.

The problem with DerelictUtilNOGC that would be endorsed is that DerelictUtil and DerelictNoGC are link-incompatible so better hide it.

As I see it, `SharedLib` can be made @nogc with minimal changes and that's probably sufficient for `@nogc` loaders. The `SharedLibLoader` doesn't need to be reused. Niche requirements mandate extra-effort.

**Comment by mdparker** [comment]
> The problem with DerelictUtilNOGC that would be endorsed is that DerelictUtil and DerelictNoGC are link-incompatible so better hide it.

The point of a separate package with its own naming convention would be to make them compatible. Now that you've put the bug in my head, it's something I will likely explore later on.

And I'm glad you mentioned SharedLib. I forgot all about it!

**Comment by mdparker** [comment]
Ah, nevermind. I've already added @nogc to SharedLib where I didn't need to reimplement anything. The only things to deal with now are the array appending and exception allocation.

**Comment by rikkimax** [comment]
I think its time that we got DerelictUtil into Phobos.
So while the @nogc aspects are very important for Guillaume, perhaps the
restructuring should be for Phobos instead?

**Comment by mdparker** [comment]
If someone wants to fork DerelictUtil and work on getting it accepted into Phobos, it's fine by me. But I have no interest in being part of the process.

**Comment by p0nce** [comment]
No interest in new Phobos things here...
